### ISSUE TITLE
dN/dS calculation with provided gene calls

### ISSUE THREAD

**Issue by AroneyS** [rhysnewell/Lorikeet#39]
Is there a way to provide gene calls (e.g. gff files) for use in the dN/dS calculation?

**Comment by rhysnewell** [comment]
Not via the command line, you can potentially spoof it though by putting the gff file you would like to use as the gene calls into the output folder for a given reference and naming it the same way that Lorikeet names the gff. That way, Lorikeet will see the file already exists and then use the existing one.

I did intend to have the user be able to provide a gff file, but it was turning out to be more work than it was worth
