### ISSUE TITLE
Lorikeet runtime

### ISSUE THREAD

**Issue by AroneyS** [rhysnewell/Lorikeet#44]
Hi Rhys, I've been running Lorikeet against a pre-mapped dataset consisting of 254 pre-indexed bam files of 1800 genomes, but it seems to be running slower than expected.

Example command (Lorikeet v0.7.3):
```bash
lorikeet call \
    -r genome.fna \
    -b 1.bam 2.bam ... \
    --calculate-fst \
    --calculate-dnds \
    --output-directory out \
    --parallel-genomes {1 or 8} \
    --threads {variable} \
```

Run 1:
11 genomes, 8 in parallel, 32 cpu/300GB total
4 genomes finished, after 120/168/192/288 hours (killed after 300 hours)

Run 2:
8 genomes, individually ran, 16 cpu/128GB each
43-151 hours wall-time (537-788 hours cpu-time)

Run 3:
8 genomes, individually ran, 16 cpu/128GB each, 61-120 bam files (subset including only those where genome present)
15-24 hours wall-time (200-329 hours cpu-time)

Are these the running times that you would expect?

**Comment by wwood** [comment]
Hi Sam,

Would be good to get this sorted. Are you able to email me the specific commands you used that work on our servers please?
TIA

**Comment by rhysnewell** [comment]
Hi Sam,

Really sorry for lack of response on this. For some reason GitHub hasn't been sending me notifications for issues opened on this repo. Something is wrong with the settings, I'll fix it going forward.

As for your question. Yes, this is either a problem with the `rust-htslib` library or file handling in general. I believe when you have a giant bam file with entries for many reference genomes and you spawn multiple threads that all try to read from that file, the file is constantly being "locked", where only one thread can read it a time. This is fairly annoying and ends up with long run times which is not great.

You'll notice that there is a `split-bams` option, this will take giant bam files and split them up based on the references being mapped to. This then lets lorikeet better multithread later on and removes any overhead required by the user i.e. manually splitting the bam files yourself

Rhys

**Comment by rhysnewell** [comment]
Addition of `--profile` parameter alleviates this issue in v0.8 and above. Various optimisations also at play here regarding parallelisation. Split bams shouldn't play a role, likely shouldn't be used in future and will be deprecated
