### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by rwolfe45** [rhysnewell/Lorikeet#6]
I am trying to install Lorikeet on our lab Linux server. I am using option2 to Install manually. When I use the command: bash install.sh I get the following error:

/opt/Miniconda2/miniconda2/envs/lorikeet
warning: `panic` setting is ignored for `bench` profile
warning: `panic` setting is ignored for `test` profile
   Compiling lorikeet-genome v0.5.1 (/opt/Miniconda2/miniconda2/envs/Lorikeet)
warning: unused import: `bird_tool_utils::command`
 --> src/estimation/linkage.rs:1:5
  |
1 | use bird_tool_utils::command;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `read_npy`, `write_npy`
 --> src/estimation/linkage.rs:7:19
  |
7 | use ndarray_npy::{read_npy, write_npy};
  |                   ^^^^^^^^  ^^^^^^^^^

error[E0308]: mismatched types
   --> src/estimation/codon_structs.rs:157:72
    |
157 |                 let codon_sequence = get_codons(&gene_sequence, frame, str                   and);
    |                                                                        ^^^                   ^^^ expected enum `Strand`, found enum `bio_types::strand::Strand`
    |
    = note: perhaps two different versions of crate `bio_types` are being used?

error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0308`.
error: could not compile `lorikeet-genome`

To learn more, run the command again with --verbose.
  Installing lorikeet-genome v0.5.1 (/opt/Miniconda2/miniconda2/envs/Lorikeet)
    Updating crates.io index
    Updating git repository `https://github.com/rhysnewell/CoverM`
    Updating git repository `https://github.com/wwood/galah`
    Updating git repository `https://github.com/wwood/checkm-rs`
   Compiling lorikeet-genome v0.5.1 (/opt/Miniconda2/miniconda2/envs/Lorikeet)
warning: unused import: `bird_tool_utils::command`
 --> src/estimation/linkage.rs:1:5
  |
1 | use bird_tool_utils::command;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused imports: `read_npy`, `write_npy`
 --> src/estimation/linkage.rs:7:19
  |
7 | use ndarray_npy::{read_npy, write_npy};
  |                   ^^^^^^^^  ^^^^^^^^^

error[E0308]: mismatched types
   --> src/estimation/codon_structs.rs:157:72
    |
157 |                 let codon_sequence = get_codons(&gene_sequence, frame, str                   and);
    |                                                                        ^^^                   ^^^ expected enum `Strand`, found enum `bio_types::strand::Strand`
    |
    = note: perhaps two different versions of crate `bio_types` are being used?

error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0308`.
error: failed to compile `lorikeet-genome v0.5.1 (/opt/Miniconda2/miniconda2/env                   s/Lorikeet)`, intermediate artifacts can be found at `/opt/Miniconda2/miniconda2                   /envs/Lorikeet/target`

Caused by:
  could not compile `lorikeet-genome`

Thanks
Rich Wolfe

**Comment by rhysnewell** [comment]
I'm going to close this now as I think this would no longer be an issue
